_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: d246ad39-4400-4303-823f-7bf77b4b4a94
name: 'Request a Use of the UCLA Marks'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/241
  front: /node/247
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
