_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 0eb6061b-a6a9-44ba-8c5d-30d345ba2460
name: 'Bruin Learn Center of Excellence'
mail: portaleditor@it.ucla.edu
slogan: 'Enabling the Future of Teaching & Learning'
page:
  403: ''
  404: /node/816
  front: /node/833
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
