_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: a60e428a-c3e2-40a2-90b5-54a39b2ba61a
name: 'Early Care and Education'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/561
  front: /node/171
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
