_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 5483ba33-8b43-40c6-b13a-ea5f30edcf64
name: Commencement
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/136
  front: /node/121
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
