_core:
  default_config_hash: Ds0RaUH1K3ZqoOsd4UBavL7kkblBrbh_8tuKswz02qk
page_title: Sitemap
message:
  value: ''
  format: sf_restricted_html
plugins:
  frontpage:
    enabled: false
  'menu:main':
    enabled: true
    weight: -46
    settings:
      title: 'Main navigation'
      show_disabled: false
    id: 'menu:main'
    provider: sitemap
  'menu:footer':
    enabled: true
    weight: -45
    settings:
      title: Footer
      show_disabled: false
    id: 'menu:footer'
    provider: sitemap
  'vocabulary:sf_article_category':
    enabled: true
    weight: -43
    settings:
      title: 'Article Categories'
      show_description: false
      show_count: false
      display_unpublished: false
      term_depth: 3
      term_count_threshold: 1
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
    id: 'vocabulary:sf_article_category'
    provider: sitemap
  'vocabulary:sf_article_type':
    enabled: true
    weight: -42
    settings:
      title: 'Article Type'
      show_description: false
      show_count: false
      display_unpublished: false
      term_depth: 3
      term_count_threshold: 1
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
    id: 'vocabulary:sf_article_type'
    provider: sitemap
  'vocabulary:sf_event_type':
    enabled: true
    weight: -41
    settings:
      title: 'Event Category'
      show_description: false
      show_count: false
      display_unpublished: false
      term_depth: 3
      term_count_threshold: 1
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
    id: 'vocabulary:sf_event_type'
    provider: sitemap
  'vocabulary:sf_photo_gallery_categories':
    enabled: true
    weight: -38
    settings:
      title: 'Photo Gallery Categories'
      show_description: false
      show_count: false
      display_unpublished: false
      term_depth: 3
      term_count_threshold: 1
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
    id: 'vocabulary:sf_photo_gallery_categories'
    provider: sitemap
  'vocabulary:sf_tags':
    enabled: true
    weight: -37
    settings:
      title: Tags
      show_description: false
      show_count: false
      display_unpublished: false
      term_depth: 3
      term_count_threshold: 1
      customize_link: false
      term_link: entity.taxonomy_term.canonical|taxonomy_term
      always_link: false
      enable_rss: false
      rss_link: view.taxonomy_term.feed_1|arg_0
      rss_depth: 9
    id: 'vocabulary:sf_tags'
    provider: sitemap
include_css: false
show_front: false
show_titles: true
show_books: {  }
books_expanded: true
show_menus:
  footer: footer
  main: main
  account: '0'
  admin: '0'
  tools: '0'
show_menus_hidden: false
show_vocabularies:
  sf_article_category: sf_article_category
  sf_article_type: sf_article_type
  sf_event_type: sf_event_type
  sf_person_type: sf_person_type
  sf_photo_gallery_categories: sf_photo_gallery_categories
  sf_tags: sf_tags
show_description: false
show_count: false
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 0
rss_taxonomy: -1
css: false
order:
  front: -50
  menus_account: -49
  menus_admin: -48
  menus_footer: -46
  menus_main: -47
  menus_tools: -45
  vocabularies_sf_article_category: -44
  vocabularies_sf_article_type: -43
  vocabularies_sf_event_type: -41
  vocabularies_sf_person_type: -40
  vocabularies_sf_photo_gallery_categories: -39
  vocabularies_sf_tags: -38
