_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 435968a9-b051-4d91-a259-ef4f237c6ad3
name: 'IT Services'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/9631
  front: /node/8201
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
