_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 17094d50-6899-40af-8399-ac815f5ea906
name: 'UCLA Central Ticket Office'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/81
  front: /node/76
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
