determine_menu: true
disable_admin_page: true
append_current_page: false
current_page_as_link: false
append_member_page: false
member_page_as_link: false
remove_home: false
add_home: true
menu_breadcrumb_menus:
  main:
    enabled: 1
    weight: -10
    taxattach: 0
  admin:
    enabled: 0
    weight: 0
    taxattach: 0
  footer:
    enabled: 0
    weight: 0
    taxattach: 0
  tools:
    enabled: 0
    weight: 0
    taxattach: 0
  account:
    enabled: 0
    weight: 0
    taxattach: 0
home_as_site_name: false
