_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 6f3f40c7-0109-4796-8436-6f77aace9060
name: 'Campus Human Resources'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: /node/35891
  404: /node/35891
  front: /node/36117
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
