_core:
  default_config_hash: MWeO7DHwIWK8pI5rMj2m6MtORb8QcpNdhnOK8FtwSTg
enable_globally: 1
enable_globally_on_admin_routes: false
default_challenge: recaptcha/reCAPTCHA
description: 'This question is for testing whether or not you are a human visitor and to prevent automated spam submissions.'
title: ''
administration_mode: false
administration_mode_on_admin_routes: false
whitelist_ips: ''
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
enabled_default: 1
allow_on_admin_pages: false
add_captcha_description: false
