<?php

/**
 * @file
 */

/**
 * Implements hook_form_alter().
 */
function sitefarm_article_form_alter(&$form, &$form_state, $form_id) {
  // Move Node Edit fields into the advanced tabs group.
  $advanced_tabs = \Drupal::service('sf.advanced_tabs')->loadForm($form);

  // Move the Article Category fields to the Categorization group.
  $advanced_tabs->moveField('field_sf_article_category', 'categorizing');

  // Move the Article Type field to the Categorization group.
  $advanced_tabs->moveField('field_sf_article_type', 'categorizing');

  // Move the Author Profile field to the Authoring Information group.
  $advanced_tabs->moveField('field_sf_authors', 'author');

  // Move the Byline field to the Authoring Information group.
  $advanced_tabs->moveField('field_sf_article_byline', 'author');

  $form = $advanced_tabs->save();

  // Unset none option from Article Category taxonomy's Brand Color field.
  if ($form_id == 'taxonomy_term_sf_article_category_form') {
    unset($form['field_sf_brand_color']['widget']['#options']['_none']);
  }
}
