<?php

/**
 * @file
 */

/**
 * Reset Media view modes for better wysiwyg integration.
 */
function sitefarm_media_update_9001(&$sandbox) {
  /** @var \Drupal\config_update\ConfigRevertInterface $config_revert */
  $config_revert = \Drupal::service('config_update.config_update');

  // Revert existing view modes.
  $config_revert->revert('entity_view_display', 'media.sf_image_media_type.photoswipe');

  return t('Reset Media view modes for Photoswipe.');
}
