<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function sitefarm_focal_link_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_ids = [
    'layout_builder_update_block',
    'layout_builder_add_block',
    'block_content_sf_focal_link_form',
    'block_content_sf_focal_link_edit_form',
  ];

  if (!in_array($form_id, $form_ids)) {
    return;
  }

  if (isset($form['settings']['block_form'])) {
    $form['settings']['block_form']['#process'][] = '_sitefarm_focal_link_form_visibility';
  }
  else {
    $form = _sitefarm_focal_link_form_visibility($form, $form_state);
  }
}

/**
 * Hide or show fields depending on the icon choice.
 *
 * @param array $element
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @return array
 */
function _sitefarm_focal_link_form_visibility(array $element, FormStateInterface $form_state) {
  $field = 'field_sf_icon_choice[value]';

  // If this is an inline block in Layout Builder.
  if (!isset($element['form_id'])) {
    $field = 'settings[block_form][field_sf_icon_choice][value]';
  }

  // Set conditional state on Image.
  $element['field_sf_m_block_primary_img']['#states'] = [
    'visible' => [
      ':input[name="' . $field . '"]' => ['checked' => FALSE],
    ],
  ];
  $element['field_sf_icons']['#states'] = [
    'visible' => [
      ':input[name="' . $field . '"]' => ['checked' => TRUE],
    ],
  ];

  return $element;
}

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * For the ID form_block.
 */
function sitefarm_focal_link_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get the Sitefarm forms helper service.
  $form_helper = \Drupal::service('sf.block_form_helpers');

  if ($form_helper->getBlockContentBundle($form_state) == 'sf_focal_link') {
    $form_helper->hideBlockTitleCheckbox($form);
  }
}

/**
 * Implements hook_preprocess_block().
 */
function sitefarm_focal_link_preprocess_block(&$variables) {
  $elements = $variables["elements"];

  // If this is a Focal Link add the Material Icon library.
  if (isset($elements['content']['#block_content']) && is_object($elements['content']['#block_content'])) {
    $bundle = $elements['content']['#block_content']->bundle();

    if (isset($bundle) && $bundle == 'sf_focal_link') {
      $variables['#attached']['library'][] = 'sitefarm_focal_link/material-icons';
    }
  }
}
