_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 1fcb291e-a25f-44b0-b441-37cd7922e986
name: 'UCLA Threat Response Task Force'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
