_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 02bc1c58-faad-40e1-83d6-0a9974552d66
name: Transportation
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/3331
  front: /node/1421
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
