<?php

/**
 * @file
 * Module for siteden taxonomy terms. */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function siteden_taxonomy_terms_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  switch ($form_id) {
    case 'taxonomy_term_sf_article_category_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    case 'taxonomy_term_sf_event_type_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    case 'taxonomy_term_sf_article_type_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    case 'taxonomy_term_sf_media_categories_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    case 'taxonomy_term_sf_units_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    case 'taxonomy_term_sf_tags_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    case 'taxonomy_term_sf_photo_gallery_categories_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    case 'taxonomy_term_sf_person_type_form':
      $form['actions']['submit']['#submit'][] = 'siteden_taxonomy_terms_submit';
      break;
    default:
      break;
  }
}

/**
 * Adds function to form submit.
 */
function siteden_taxonomy_terms_submit($form, FormStateInterface &$form_state) {
  $name = $form_state->getValue('name')[0]['value'];
	if (str_contains($name, '-')) {
    $name = str_replace('-', ' ', $name);
		$database = \Drupal::service('database');
		$num_updated = $database->update('taxonomy_term_field_data')
		  ->fields([
		    'name' => $name,
		  ])
		  ->condition('tid', $form_state->getformObject()->getEntity()->id(), '=')
		  ->execute();
	}
}
