_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: e4ef674e-2488-44ae-8f9d-4c286d57dfe1
name: 'Office of Emergency Management'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/231
  front: /node/226
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
