_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 79226d8c-ea05-40f7-8417-2154a925e03a
name: 'FACET Program'
mail: portaleditor@it.ucla.edu
slogan: facet@it.ucla.edu
page:
  403: ''
  404: /node/191
  front: /node/202
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
