name: 'Component Configuration'
description: 'Feature for managing configuration for components.'
type: module
core_version_requirement: '^9.4 || ^10'
dependencies:
  - 'allowed_formats:allowed_formats'
  - 'block_field:block_field'
  - 'drupal:block_content'
  - 'drupal:field'
  - 'drupal:link'
  - 'drupal:media'
  - 'drupal:media_library'
  - 'drupal:options'
  - 'drupal:text'
  - 'drupal:views'
  - 'entity_reference_revisions:entity_reference_revisions'
  - 'layout_paragraphs:layout_paragraphs'
  - 'paragraphs:paragraphs'
  - 'paragraphs_type_permissions:paragraphs_type_permissions'
  - 'sitefarm_core:sitefarm_core'
  - 'sitefarm_image_styles:sitefarm_image_styles'
  - 'sitefarm_media:sitefarm_media'
  - 'style_options:style_options'
  - 'viewfield:viewfield'
package: SiteFarm
