_core:
  default_config_hash: KZiV2LB312xgJBphfq5BTjmp16xiR5KM8InBJ-pff7Y
favicon:
  mimetype: image/vnd.microsoft.icon
  path: profiles/custom/siteden/favicon.ico
  url: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: profiles/custom/siteden/sitefarm_logo.svg
  url: ''
  use_default: false
