_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: b42f6381-1bea-4a68-9d56-3d7c6d44f049
name: 'Business & Finance Solutions'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/3166
  front: /node/3056
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
