block.settings.bso_status_alert_block:
  type: block_settings
  label: 'Site Status Alert'
  mapping:
    site_status:
      type: string
      label: 'Site Status'
    status_message:
      type: string
      label: 'Status Message'     