_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: cacd418d-8488-4f9b-99dd-d6b3363a9726
name: 'Mail, Document & Distribution Services'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/216
  front: /node/201
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
