_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 1b3c911b-41a5-40a9-b8b8-e76a0e763401
name: 'Travel Services'
mail: portaleditor@it.ucla.edu
slogan: 'Travel Services'
page:
  403: ''
  404: /node/1261
  front: /node/1171
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
