<?php

/**
 * @file
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\UserInterface;

/**
 * Implements hook_user_login().
 */
function siteden_sso_user_login(UserInterface $account) {
  $middleware = \Drupal::service('siteden_sso.http_middleware');

  // We want user to be redirected to the homepage after login.
  $response = new RedirectResponse("/node");
  $middleware->setRedirectResponse($response);
  return;
}
