_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: cddec5ba-9fa7-47bd-ac58-74c6dbd9e914
name: 'Events Office'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/646
  front: /node/631
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
