_core:
  default_config_hash: MWeO7DHwIWK8pI5rMj2m6MtORb8QcpNdhnOK8FtwSTg
enable_globally: 1
enable_globally_on_admin_routes: false
default_challenge: recaptcha/reCAPTCHA
description: ''
administration_mode: false
administration_mode_on_admin_routes: false
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
default_validation: 1
persistence: 0
enable_stats: true
log_wrong_responses: false
title: CAPTCHA
