_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  standard__front_page:
    menu_name: main
    parent: 'menu_link_content:dca90144-5a88-4052-9509-6904dd6b2bc0'
    weight: -48
    expanded: false
    enabled: false
