_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: a09006ef-710a-4cbe-ad09-71a1c11cc8d9
name: Ergonomics
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/756
  front: /node/686
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
