<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function ck_columns_theme($existing, $type, $theme, $path) {
  return [
    'layout_columns' => [
      'variables' => [
        'class' => NULL,
        'columns' => NULL,
        'layout' => NULL,
        'gap' => NULL,
        'cwidth' => NULL,
        'force' => FALSE,
        'vmargin' => NULL,
        'column1' => NULL,
        'column2' => NULL,
        'column3' => NULL,
        'column4' => NULL,
      ],
    ],
  ];
}
