_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 4de217c7-2cda-44ee-b415-40181fdc44a5
name: 'Purchasing & Accounts Payable'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/1891
  front: /node/1791
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
