services:
  config_suite.config_subscriber:
    class: Drupal\config_suite\ConfigSuiteExportSubscriber
    arguments: ['@router.builder']
    tags:
      - { name: event_subscriber }
  page_load.config_subscriber:
    class: Drupal\config_suite\ConfigSuiteImportSubscriber
    arguments: ['@config.factory']
    tags:
      - { name: event_subscriber }
