_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 43188274-2059-463c-82d2-fad14a687fc4
name: 'HR Transformation'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/6
  front: /node/6
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
