_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: c09bd8a4-92d7-464d-adc8-08973183933e
name: 'Office of the Chief Information Security Officer'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/1611
  front: /node/1551
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: "<p>security@ucla.edu</p>\r\n"
  format: sf_basic_html
