_core:
  default_config_hash: quVyW1C7KpL2dhVF4Asx5lBFtGOMqwCRM2uOw8RcsQ4
automatic_import: false
automatic_export: false
dependencies:
  module:
    - config_suite
  enforced:
    module:
      - config_suite
