_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 84cbeeec-2ab2-4d25-ae97-7bf0bed0ed32
name: Compliance
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/86
  front: /node/87
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
