_core:
  default_config_hash: oqQElnvorzLoHb68o4B3zFkGuMV5_GQEGi7pHfUseVM
fetcher: aggregator
parser: aggregator
processors:
  - aggregator
items:
  expire: 9676800
source:
  list_max: 3
normalize_post_dates: false
