_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: eeffab0f-9026-4f61-8f22-d1e2f5e17952
name: 'Research & Creative Activities'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/3651
  front: /node/2641
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
