_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 9c858e81-2d35-4ef0-a48b-476b8249ab98
name: 'Academic Affairs and Personnel'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/2296
  front: /node/2051
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
