_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 9c32ecf2-d925-49af-a0e3-e3e2d303d8a2
name: Facilities
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/86
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
