<?php

/**
 * @file
 */

/**
 * Implements hook_page_attachments().
 */
function siteden_embed_js_page_attachments(array &$attachments) {
  $embed_js_config = \Drupal::config('siteden_embed_js.js_settings')->get('embed_js') ?? '';

  // Embed JS into pages, if configured by admin.
  if (!empty($embed_js_config)) {
    $embed_index = 0;
    foreach ($embed_js_config as $js_link => $values) {
      // Allow only if JS link provided only.
      if ($js_link) {
        $embed_js_drupal_paths = is_array($values['embed_js_page']) ? $values['embed_js_page'] : 'global';
        $current_path = \Drupal::service('path.current')->getPath();
        $current_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

        $path_matches = FALSE;
        if ($embed_js_drupal_paths == 'global') {
          $path_matches = TRUE;
        }
        else {
          foreach ($embed_js_drupal_paths as $embed_js_path) {
            if (\Drupal::service('path.matcher')->matchPath($current_alias, $embed_js_path)) {
              $path_matches = TRUE;
              break;
            }
          }
        }

        if ($path_matches) {
          // Embed JS either specific pages or throughout the applications.
          $attachments['#attached']['html_head'][] = [
            [
              '#type' => 'html_tag',
              '#tag' => $values['embed_js_type'],
              '#attributes' => [
                'src' => str_replace('@', '.', $js_link),
                'async' => $values['embed_js_async'],
              ],
            ],
            'custom-embed-js-' . $embed_index,
          ];
          $embed_index++;
        }
      }
    }
  }
}
