_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 5bff8b76-fe26-4f98-94cf-b7adf97b8c23
name: 'Sustainable LA Grand Challenge'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/4011
  front: /node/3736
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
