_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
