_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 9a12700b-0d90-49fd-b63e-26ac9310d5f4
name: 'HR & Payroll Operations Center - South'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/271
  front: /node/261
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
