_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: d59439fb-451c-47e4-8015-18a2f67c5f96
name: 'Administration Marketing & Communications'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/23
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
