_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 260072b1-058a-4ed4-94d5-7bea01e20d43
name: 'Real Estate Services'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/116
  front: /node/121
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
