_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  standard__front_page:
    menu_name: main
    parent: ''
    weight: 7
    expanded: false
    enabled: false
  search__view:
    enabled: false
    menu_name: tools
    parent: ''
    expanded: false
    weight: 0
