_core:
  default_config_hash: HM89l2a_SP7lC9C_a_THjoKamMbJ1Ne7yTPQpPBQ6bI
protect_all_forms: false
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  node_sf_article_form: false
  node_sf_event_form: false
  node_sf_landing_form: false
  node_sf_page_form: false
  node_sf_person_form: false
  node_sf_photo_gallery_form: false
