_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: c02468f2-520c-4a5a-9d45-039d71af283d
name: 'Environment, Health & Safety'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/3711
  front: /node/3241
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
