_core:
  default_config_hash: bXMvdgo18cgC30d3IrdJu_y0H6APQmYeFP-2uzzhuBw
langcode: en
activate: true
auth_source: default-sp
login_link_display_name: 'Login with your SSO account'
login_link_show: true
user_name: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6'
unique_id: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6'
mail_attr: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6'
header_no_cache: false
role:
  population: ''
  eval_every_time: false
register_users: true
allow:
  set_drupal_pwd: true
  default_login: true
  default_login_roles:
    authenticated: authenticated
    contributor: contributor
    editor: editor
    site_manager: site_manager
    site_builder: site_builder
    administrator: administrator
  default_login_users: '1'
logout_goto_url: ''
user_register_original: admin_only
sync:
  mail: true
  user_name: true
autoenablesaml: true
debug: false
secure: false
httponly: false
