_core:
  default_config_hash: i8rfiyZ9RbGpAHZN9urU6PZsYynhwWXsiM-MdFj1zt4
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
surface_next: 1
