_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: ba4e1af3-f267-4df9-9fcb-dc0943e08ed8
name: 'Reimagine IT: Talent'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
