_core:
  default_config_hash: 9H5fQPx4k6A8CtKV3LNhib2bGCYZhQQvcbG_apcrgtg
smtp_on: true
smtp_host: smtp.office365.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: ais_portaleditor@ad.ucla.edu
smtp_password: ChangeITS$
smtp_from: portaleditor@it.ucla.edu
smtp_fromname: 'UCLA Web Services'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: shill@it.ucla.edu
smtp_reroute_address: ''
smtp_debugging: true
smtp_keepalive: false
