_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 03df5428-e9f5-4998-b1c1-fe1a5b8a7369
name: 'UCLA Central Resource Unit'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/721
  front: /node/376
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
