_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  address: 0
  admin_toolbar: 0
  allowed_formats: 0
  anchor_link: 0
  automated_cron: 0
  block: 0
  block_content: 0
  block_field: 0
  block_style_plugins: 0
  breakpoint: 0
  captcha: 0
  ck_autosave: 0
  ck_columns: 0
  ck_feature_block: 0
  ck_media_link: 0
  ckeditor: 0
  ckeditor_descriptionlist: 0
  ckwordcount: 0
  components: 0
  config: 0
  config_ignore: 0
  config_split: 0
  config_suite: 0
  config_update: 0
  content_moderation: 0
  contextual: 0
  convert_bundles: 0
  crop: 0
  css_editor: 0
  ctools: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  editor_file: 0
  editoria11y: 0
  embed: 0
  entity_reference_revisions: 0
  fakeobjects: 0
  features: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  gin_toolbar: 0
  google_analytics: 0
  google_cse: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_block_title_automatic: 0
  layout_builder: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  lock_sitefarm_features: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_firstchild: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  mysql: 0
  node: 0
  notification: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  permissions_filter: 0
  photoswipe: 0
  phpass: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  robotstxt: 0
  roleassign: 0
  rss_feed_block: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  select2: 0
  shortcut: 0
  simple_sitemap: 0
  site_credits: 0
  siteden_admin_custom: 0
  siteden_articles_slider: 0
  siteden_blocks: 0
  siteden_components: 0
  siteden_events_slider: 0
  siteden_hashed_fields_convert: 0
  siteden_menu_item_limit: 0
  siteden_permissions_controller: 0
  siteden_photo_slider: 0
  siteden_update: 0
  sitefarm_article: 0
  sitefarm_article_banner: 0
  sitefarm_basic_block: 0
  sitefarm_branding: 0
  sitefarm_call_to_action: 0
  sitefarm_captcha: 0
  sitefarm_card: 0
  sitefarm_component_configuration: 0
  sitefarm_core: 0
  sitefarm_custom_social_links: 0
  sitefarm_event: 0
  sitefarm_featured_articles_and_events: 0
  sitefarm_focal_link: 0
  sitefarm_focus_box: 0
  sitefarm_hero_banner: 0
  sitefarm_image_styles: 0
  sitefarm_landing: 0
  sitefarm_marketing_highlight: 0
  sitefarm_media: 0
  sitefarm_media_entity_token: 0
  sitefarm_page: 0
  sitefarm_person: 0
  sitefarm_photo_gallery: 0
  sitefarm_simple_configuration: 0
  sitefarm_summary: 0
  sitefarm_taxonomy: 0
  sitefarm_university_header: 0
  sitefarm_workflows: 0
  sitefarm_wysiwyg: 0
  sitemap: 0
  smtp: 0
  social_media_links: 0
  style_options: 0
  svg_image_field: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  url_embed: 0
  user: 0
  viewfield: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workbench_email: 0
  workflows: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  siteden: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  siteden_surface: 0
  claro: 0
  gin: 0
profile: siteden
