_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: eb4c2be3-30ea-40fc-8cdc-3934739abb30
name: 'Bruins Safe Online'
mail: portaleditor@it.ucla.edu
slogan: 'UCLA Emergency Website'
page:
  403: ''
  404: /node/916
  front: /node/26
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
