_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 1dfea7f9-a1b1-433c-a325-4c14a36464a1
name: Housing
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/2746
  front: /node/2951
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
