_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: b1c2e2c2-5aef-4345-a836-7bfdfa7055c9
name: 'Campus Services'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/171
  front: /node/161
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
