<?php

/**
 * @file
 * Install, update and uninstall functions for the SiteFarm Image Styles module.
 */

/**
 * Re-import the banner background image style.
 */
function sitefarm_image_styles_update_9001() {
  /** @var \Drupal\config_update\ConfigReverter $config_revert */
  $config_revert = \Drupal::service('config_update.config_update');
  $config_revert->revert('image_style', 'sf_hero_banner_bg');
}
