_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 73adb90b-af79-45f0-b5cf-f65f7e8d0e97
name: 'Women in Tech'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/66
  front: /node/56
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
