_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 4ec8a14a-0f45-4e50-8901-93265fc6dce0
name: 'Web Services'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/83
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
