_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: f0e66624-9b5d-4abf-9785-a9b35e921a23
name: 'Academic Senate'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/1046
  front: /node/1036
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
