_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  user__page:
    menu_name: account
    parent: ''
    weight: -10
    expanded: false
    enabled: false
  standard__front_page:
    weight: -100
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: -45
    expanded: false
    enabled: false
