_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: ed32a53c-7353-410a-bacd-b49beef25225
name: Insiders
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/7096
  front: /node/9087
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
