/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function (Drupal, debounce, CKEDITOR, $, displace, AjaxCommands) {
  if (AjaxCommands) {
    setTimeout(function() {
      $(".cke_combo_button").click(function(){
            setTimeout(function() { 
                cke_container = document.querySelector('.ui-dialog');
                cke_stylebox = document.querySelector('.cke_combopanel');
                container_top = parseInt(cke_container.style.top) + 148;
                stylebox_left = parseInt(cke_stylebox.style.left);
                $(".cke_combopanel").attr('style',"position: fixed !important; top:"+container_top+"px !important; z-index: 10001; opacity: 1; left: "+stylebox_left+"px !important");
            }, 300);
      })
      $(window).on('scroll', function (e){
          if ($('.cke_combopanel').is(':visible')){                       
              cke_container = document.querySelector('.ui-dialog');
              cke_stylebox = document.querySelector('.cke_combopanel');
              container_top = parseInt(cke_container.style.top) + 148;
              stylebox_left = parseInt(cke_stylebox.style.left);
              $(".cke_combopanel").attr('style',"position: fixed !important; top:"+container_top+"px !important; z-index: 10001; opacity: 1; left: "+stylebox_left+"px !important");
          }
      });
    }, 800);
  }
})(Drupal, Drupal.debounce, CKEDITOR, jQuery, Drupal.displace, Drupal.AjaxCommands);
