_core:
  default_config_hash: 1dLjcVBPjJ8_ba7MxLYtb19C6KdrsGdjTYbkA5vFKIQ
determine_menu: true
disable_admin_page: true
append_current_page: false
current_page_as_link: false
stop_on_first_match: false
append_member_page: false
member_page_as_link: false
remove_home: false
add_home: true
front_title: null
exclude_empty_url: false
exclude_disabled_menu_items: false
derived_active_trail: false
menu_breadcrumb_menus:
  main:
    enabled: 1
    weight: -10
    taxattach: 0
    langhandle: 0
  admin:
    enabled: 0
    weight: -9
    taxattach: 0
    langhandle: 0
  footer:
    enabled: 0
    weight: -8
    taxattach: 0
    langhandle: 0
  tools:
    enabled: 0
    weight: -7
    taxattach: 0
    langhandle: 0
  ems-navigation:
    enabled: 0
    weight: -6
    taxattach: 0
    langhandle: 0
  account:
    enabled: 0
    weight: -5
    taxattach: 0
    langhandle: 0
home_as_site_name: false
