_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 7cf4c39c-6b15-42d3-aba5-a684ce1bbbe0
name: 'Police Department'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/736
  front: /node/671
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
