<?php

/**
 * @file
 */

/**
 * Implements hook_element_info_alter().
 */
function siteden_ckeditor_configs_element_info_alter(array &$info) {
  if (isset($info['textarea'])) {
    $info['textarea']['#attached']['library'][] = 'siteden_ckeditor_configs/siteden_ckeditor_configs.ckeditor';
  }
}

/**
 * Implements hook_embed_type_plugins_alter().
 */
/*function sitefarm_wysiwyg_embed_type_plugins_alter(array &$plugins) {
  // Replace the default Url Embed class with our own so that the default image
  // can be replaced.
  if (isset($plugins['url']['class'])) {
    $plugins['url']['class'] = 'Drupal\sitefarm_wysiwyg\UrlEmbed';
  }
} */

/**
 * Implements hook_form_alter().
 */
/*function sitefarm_wysiwyg_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'editor_media_dialog') {
    // Add a custom submit handler to use a default caption on wysiwyg media.
    $form['#submit'][] = '_sitefarm_wysiwyg_wysiwyg_caption_submit';
  }
}*/

/**
 * Submit Handler for form alter to use a media's default field caption.
 *
 * //@param $form
 * //@param \Drupal\Core\Form\FormStateInterface $form_state
 */
/*function _sitefarm_wysiwyg_wysiwyg_caption_submit(&$form, FormStateInterface $form_state) {
  if ($form_state->getValue('hasCaption')) {
    $storage = $form_state->getStorage();
    if (empty($storage['media_embed_element']['data-caption'])) {
      $media = \Drupal::service('entity.repository')->loadEntityByUuid('media', $storage['media_embed_element']['data-entity-uuid']);
      $caption = $media->field_sf_media_caption->value;
      if ($caption) {
        $form_state->setValue(['attributes', 'data-caption'], $caption);
      }
    }
  }
}*/
