_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 55d7c2f5-3975-4054-9499-ec432692e401
name: 'Insurance & Risk Management'
mail: portaleditor@it.ucla.edu
slogan: ''
page:
  403: ''
  404: /node/681
  front: /node/661
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
credit_info:
  value: ''
  format: sf_basic_html
