name: 🛞 Backstop Reference Test

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 20

defaults:
  run:
    shell: bash

jobs:
  reference-test:
    name: reference-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Setup Node & Cache
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: "execute test"
        run: npm run reference-test
        continue-on-error: true

      - name: "debug test"
        run: backstop openReport
        continue-on-error: true

      - name: Save HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: html_reports
          path: backstop_test
          overwrite: true
          include-hidden-files: true

      - name: Save logs (only if failed)
        uses: actions/upload-artifact@v4
        with:
          name: test_logs
          path: backstop_test
          overwrite: true
          include-hidden-files: true
